openapi: 3.0.0
paths:
  '/user':
    $ref: "paths/user.yml" 

  '/user?action=login': 
    post:
      operationId: login
  '/user/{id}':
    get:
      operationId: getUserById
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
  '/blog':
    get:
      operationId: getBlogsByPage
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int64